name: Build & Deploy Django

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          . venv/bin/activate
          python manage.py test

      - name: Collect static files
        run: |
          . venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Upload static files
        uses: actions/upload-artifact@v4
        with:
          name: static-files
          path: static/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download static files
        uses: actions/download-artifact@v4
        with:
          name: static-files
          path: static/

      - name: Sync static files to S3
        run: |
          aws s3 sync static/ s3://your-s3-bucket/static/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'your-aws-region'

      - name: Deploy to EC2
        run: |
          scp -i your-key.pem -r . ec2-user@your-ec2-instance:/path/to/your/project
          ssh -i your-key.pem ec2-user@your-ec2-instance 'cd /path/to/your/project && docker-compose down && docker-compose up -d'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'your-aws-region'
